package com.vishwas.memory;

import com.vishwas.config.VishwasProperties;
import com.vishwas.ingest.Vendor;
import com.vishwas.memory.hindsight.HindsightClient;
import com.vishwas.memory.hindsight.HindsightException;
import com.vishwas.memory.hindsight.KnowledgeNode;
import com.vishwas.memory.hindsight.KnowledgePage;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Optional;

/**
 * One knowledge-base page per vendor under a "Vendors" folder (Vendors/&lt;legal name&gt;), generated by Hindsight
 * from that vendor's memories only (the page is scoped by the vendor tag). Used for the vendor dossier export.
 */
@Component
public class KnowledgePages {

    private static final Logger log = LoggerFactory.getLogger(KnowledgePages.class);
    static final String FOLDER = "Vendors";

    private final HindsightClient hindsight;
    private final String bankId;

    public KnowledgePages(HindsightClient hindsight, VishwasProperties props) {
        this.hindsight = hindsight;
        this.bankId = props.hindsight().bankId();
    }

    static String sourceQuery(Vendor v) {
        return "Write a dossier on " + v.getLegalName() + " (GSTIN " + v.getGstin() + "). For each dimension (filing timing, "
                + "amount accuracy, tax head correctness, invoice format, responsiveness, duplicates) say what happened, with "
                + "month, invoice, amount in rupees and outcome. List promises made and whether they were kept, Vishwas's "
                + "recommendations and whether they proved right, and keep open exposure, confirmed loss and recovered "
                + "amounts separate. Say plainly where history is thin. Markdown with a short section per dimension.";
    }

    /** Creates the folder and any missing vendor pages. Idempotent; failures are logged, never thrown. */
    public int ensureVendorPages(List<Vendor> vendors) {
        try {
            List<KnowledgeNode> roots = hindsight.knowledgeTree(bankId);
            KnowledgeNode folder = roots.stream().filter(n -> "folder".equals(n.kind()) && FOLDER.equals(n.name())).findFirst()
                    .orElseGet(() -> hindsight.createFolder(bankId, FOLDER, null));
            int created = 0;
            for (Vendor v : vendors) {
                boolean exists = folder.childNodes().stream().anyMatch(n -> v.getLegalName().equals(n.name()));
                if (!exists) {
                    hindsight.createPage(bankId, v.getLegalName(), sourceQuery(v), folder.id(), List.of(MemoryWriter.vendorTag(v.getGstin())));
                    created++;
                }
            }
            return created;
        } catch (HindsightException e) {
            log.warn("Knowledge pages could not be prepared: {}", e.getMessage());
            return 0;
        }
    }

    /** The vendor's page (markdown with frontmatter), if it exists yet. */
    public Optional<KnowledgePage> vendorPage(Vendor v) {
        List<KnowledgeNode> roots = hindsight.knowledgeTree(bankId);
        return roots.stream().filter(n -> FOLDER.equals(n.name())).flatMap(f -> f.childNodes().stream())
                .filter(n -> "page".equals(n.kind()) && v.getLegalName().equals(n.name()))
                .findFirst()
                .map(n -> hindsight.getPage(bankId, n.id()));
    }
}
