-- Vishwas schema, part 1: vendor master, imported files, invoice rows, and mismatches with their outcomes.
-- Portable SQL: runs on H2 (local) and PostgreSQL (production).

CREATE TABLE vendor (
    gstin           VARCHAR(15)  NOT NULL PRIMARY KEY,
    legal_name      VARCHAR(255) NOT NULL,
    city            VARCHAR(255),
    state_code      VARCHAR(2),
    email           VARCHAR(255),
    contact_person  VARCHAR(255),
    phone           VARCHAR(255),
    supplies        VARCHAR(255)
);

CREATE TABLE import_batch (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period       VARCHAR(7)   NOT NULL,
    source       VARCHAR(10)  NOT NULL,
    filename     VARCHAR(255),
    row_count    INTEGER      NOT NULL,
    imported_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    sha256       VARCHAR(64),
    CONSTRAINT uq_import_batch UNIQUE (period, source)
);

CREATE TABLE invoice_record (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id               BIGINT       NOT NULL REFERENCES import_batch (id),
    period                 VARCHAR(7)   NOT NULL,
    source                 VARCHAR(10)  NOT NULL,
    kind                   VARCHAR(12)  NOT NULL,
    supplier_gstin         VARCHAR(15)  NOT NULL,
    supplier_name          VARCHAR(255),
    invoice_no             VARCHAR(40)  NOT NULL,
    invoice_no_norm        VARCHAR(40)  NOT NULL,
    invoice_date           DATE,
    taxable_value          NUMERIC(14, 2),
    igst                   NUMERIC(14, 2),
    cgst                   NUMERIC(14, 2),
    sgst                   NUMERIC(14, 2),
    rate                   NUMERIC(5, 2),
    hsn                    VARCHAR(10),
    description            VARCHAR(255),
    place_of_supply        VARCHAR(2),
    voucher_no             VARCHAR(30),
    booking_date           DATE,
    filed_on               DATE,
    filing_period          VARCHAR(7),
    original_invoice_no    VARCHAR(40),
    original_invoice_date  DATE
);
CREATE INDEX ix_invoice_period_source ON invoice_record (period, source);
CREATE INDEX ix_invoice_gstin ON invoice_record (supplier_gstin);

CREATE TABLE mismatch (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period               VARCHAR(7)    NOT NULL,
    vendor_gstin         VARCHAR(15)   NOT NULL,
    vendor_name          VARCHAR(255),
    type                 VARCHAR(24)   NOT NULL,
    dimension            VARCHAR(24)   NOT NULL,
    status               VARCHAR(12)   NOT NULL,
    books_record_id      BIGINT,
    gstr2b_record_id     BIGINT,
    invoice_no_books     VARCHAR(40),
    invoice_no_gstr2b    VARCHAR(40),
    invoice_no_norm      VARCHAR(40),
    invoice_date_books   DATE,
    invoice_date_gstr2b  DATE,
    taxable_books        NUMERIC(14, 2),
    taxable_gstr2b       NUMERIC(14, 2),
    itc_books            NUMERIC(14, 2),
    itc_gstr2b           NUMERIC(14, 2),
    exposure             NUMERIC(14, 2) NOT NULL,
    differences_json     VARCHAR(4000),
    candidates_json      VARCHAR(8000),
    linked_mismatch_id   BIGINT,
    note                 VARCHAR(500),
    detected_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    verdict              VARCHAR(24),
    verdict_period       VARCHAR(7),
    verdict_at           TIMESTAMP WITH TIME ZONE,
    months_late          INTEGER,
    recovered_amount     NUMERIC(14, 2) NOT NULL DEFAULT 0,
    confirmed_loss       NUMERIC(14, 2) NOT NULL DEFAULT 0,
    verdict_note         VARCHAR(500)
);
CREATE INDEX ix_mismatch_period ON mismatch (period);
CREATE INDEX ix_mismatch_vendor ON mismatch (vendor_gstin, dimension);
CREATE INDEX ix_mismatch_status ON mismatch (status);
