-- Vishwas schema, part 2: vendor communications and promises, accountant actions, recommendations
-- (the learning loop), advice runs, and the memory batches of the history load.

ALTER TABLE mismatch ADD COLUMN evidence_record_id BIGINT;

CREATE TABLE vendor_communication (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_gstin        VARCHAR(15)   NOT NULL,
    occurred_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    direction           VARCHAR(3)    NOT NULL,
    channel             VARCHAR(10)   NOT NULL,
    author              VARCHAR(255),
    summary             VARCHAR(1000) NOT NULL,
    invoice_refs        VARCHAR(500),
    promise_by          DATE,
    promise_status      VARCHAR(10),
    promise_checked_at  TIMESTAMP WITH TIME ZONE,
    attachment          VARCHAR(255),
    source              VARCHAR(10)   NOT NULL
);
CREATE INDEX ix_comm_vendor ON vendor_communication (vendor_gstin, occurred_at);

CREATE TABLE accountant_action (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_gstin  VARCHAR(15)   NOT NULL,
    mismatch_id   BIGINT,
    occurred_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    actor         VARCHAR(255)  NOT NULL,
    action        VARCHAR(30)   NOT NULL,
    note          VARCHAR(1000),
    approved_by   VARCHAR(255)
);
CREATE INDEX ix_action_vendor ON accountant_action (vendor_gstin, occurred_at);

CREATE TABLE advice_run (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period         VARCHAR(7)   NOT NULL,
    started_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at    TIMESTAMP WITH TIME ZONE,
    status         VARCHAR(10)  NOT NULL,
    mode           VARCHAR(10)  NOT NULL,
    vendors_total  INTEGER      NOT NULL,
    vendors_done   INTEGER      NOT NULL,
    message        VARCHAR(1000),
    duration_ms    BIGINT
);

CREATE TABLE recommendation (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mismatch_id         BIGINT        NOT NULL REFERENCES mismatch (id),
    run_id              BIGINT,
    vendor_gstin        VARCHAR(15)   NOT NULL,
    dimension           VARCHAR(24)   NOT NULL,
    category            VARCHAR(16)   NOT NULL,
    source              VARCHAR(10)   NOT NULL,
    headline            VARCHAR(600),
    next_step           VARCHAR(600),
    causes_json         VARCHAR(4000),
    evidence_refs_json  VARCHAR(2000),
    memory_facts_json   VARCHAR(12000),
    guardrails_json     VARCHAR(1000),
    vendor_summary      VARCHAR(1500),
    rule_id             VARCHAR(20),
    confidence_level    VARCHAR(8),
    confidence_text     VARCHAR(300),
    history_cases       INTEGER,
    model_confidence    VARCHAR(8),
    top_cause           VARCHAR(24),
    predicted_outcome   VARCHAR(24),
    baseline_action     VARCHAR(600),
    baseline_category   VARCHAR(40),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    decision            VARCHAR(10),
    decision_reason     VARCHAR(20),
    decision_note       VARCHAR(600),
    modified_step       VARCHAR(600),
    decided_by          VARCHAR(255),
    decided_at          TIMESTAMP WITH TIME ZONE,
    was_correct         BOOLEAN,
    actual_outcome      VARCHAR(24),
    judged_at           TIMESTAMP WITH TIME ZONE
);
CREATE INDEX ix_rec_mismatch ON recommendation (mismatch_id, created_at);
CREATE INDEX ix_rec_vendor ON recommendation (vendor_gstin);

CREATE TABLE memory_batch (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label         VARCHAR(40)  NOT NULL,
    period        VARCHAR(7),
    items         INTEGER      NOT NULL,
    status        VARCHAR(12)  NOT NULL,
    operation_id  VARCHAR(80),
    started_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at   TIMESTAMP WITH TIME ZONE
);
