-- Vishwas schema, part 3: the action center (case state, owner, due date, notes, reminders), the audit of
-- corrections made to memory ("Correct this history"), and month-end close sign-offs.

CREATE TABLE case_file (
    mismatch_id  BIGINT       NOT NULL PRIMARY KEY REFERENCES mismatch (id),
    state        VARCHAR(20)  NOT NULL,
    owner        VARCHAR(255),
    due_date     DATE,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by   VARCHAR(255)
);

CREATE TABLE case_note (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mismatch_id  BIGINT        NOT NULL REFERENCES mismatch (id),
    author       VARCHAR(255)  NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    text         VARCHAR(2000) NOT NULL
);
CREATE INDEX ix_note_case ON case_note (mismatch_id, created_at);

CREATE TABLE reminder (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mismatch_id  BIGINT        NOT NULL REFERENCES mismatch (id),
    due_on       DATE          NOT NULL,
    text         VARCHAR(500)  NOT NULL,
    done         BOOLEAN       NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by   VARCHAR(255)
);
CREATE INDEX ix_reminder_due ON reminder (done, due_on);

CREATE TABLE memory_correction (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    memory_id     VARCHAR(80)   NOT NULL,
    vendor_gstin  VARCHAR(15),
    action        VARCHAR(12)   NOT NULL,
    old_text      VARCHAR(4000),
    new_text      VARCHAR(4000),
    reason        VARCHAR(1000) NOT NULL,
    actor         VARCHAR(255)  NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    status        VARCHAR(12)   NOT NULL,
    error         VARCHAR(1000)
);
CREATE INDEX ix_correction_vendor ON memory_correction (vendor_gstin, created_at);

CREATE TABLE close_signoff (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period      VARCHAR(7)    NOT NULL,
    item        VARCHAR(30)   NOT NULL,
    signed_by   VARCHAR(255)  NOT NULL,
    signed_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    note        VARCHAR(1000),
    CONSTRAINT uq_signoff UNIQUE (period, item)
);
