package com.vishwas.workflow;

import com.vishwas.config.VishwasProperties;
import com.vishwas.ingest.Fmt;
import com.vishwas.ingest.VendorRepository;
import com.vishwas.memory.MemoryPublisher;
import com.vishwas.memory.MemoryWriter;
import com.vishwas.outcomes.VendorCommunication;
import com.vishwas.outcomes.VendorCommunicationRepository;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Clock;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.Optional;

/**
 * Upload a vendor's letter or e-mail (PDF). It is stored locally, recorded on the vendor thread (with any
 * promised date, which the promise tracker will later judge), and sent to Hindsight through /files/retain with
 * the vendor's tags, so the letter's own words become evidence.
 */
@Service
public class LetterService {

    static final long MAX_BYTES = 10L * 1024 * 1024;

    private final VendorCommunicationRepository communications;
    private final VendorRepository vendors;
    private final MemoryWriter writer;
    private final MemoryPublisher publisher;
    private final Clock clock;
    private final Path uploads;

    public LetterService(VendorCommunicationRepository communications, VendorRepository vendors, MemoryWriter writer,
                         MemoryPublisher publisher, Clock clock, VishwasProperties props) {
        this.communications = communications;
        this.vendors = vendors;
        this.writer = writer;
        this.publisher = publisher;
        this.clock = clock;
        this.uploads = Path.of("data", "uploads", props.hindsight().bankId());
    }

    public record Uploaded(long communicationId, String attachment, boolean sentToMemory, List<String> operationIds) {
    }

    public Uploaded upload(String gstin, String originalName, byte[] pdf, LocalDate receivedOn, String summary,
                           LocalDate promiseBy, List<String> invoices, String from) {
        vendors.findById(gstin).orElseThrow(() -> new NoSuchElementException("Unknown vendor " + gstin));
        if (pdf == null || pdf.length < 5 || !new String(pdf, 0, 5, StandardCharsets.ISO_8859_1).equals("%PDF-")) {
            throw new IllegalArgumentException("Please upload a PDF file.");
        }
        if (pdf.length > MAX_BYTES) {
            throw new IllegalArgumentException("The letter is larger than 10 MB.");
        }
        if (summary == null || summary.isBlank()) {
            throw new IllegalArgumentException("Summarise what the letter says.");
        }
        ZoneId zone = clock.getZone();
        Instant at = receivedOn == null ? Instant.now(clock) : receivedOn.atTime(12, 0).atZone(zone).toInstant();
        String name = gstin.toLowerCase() + "-" + Fmt.period(at) + "-" + System.currentTimeMillis() % 100000 + ".pdf";
        try {
            Files.createDirectories(uploads);
            Files.write(uploads.resolve(name), pdf);
        } catch (IOException e) {
            throw new UncheckedIOException("Could not store the letter", e);
        }
        VendorCommunication c = communications.save(new VendorCommunication(gstin, at, VendorCommunication.Direction.IN,
                VendorCommunication.Channel.LETTER, from, summary.trim(), invoices, promiseBy, name, "APP"));
        publisher.publish("Vendor letter " + Fmt.day(at), Fmt.period(at), List.of(writer.communication(c)));
        List<String> ops = publisher.publishFiles(List.of(writer.letter(c, pdf)));
        return new Uploaded(c.getId(), name, !ops.isEmpty(), ops);
    }

    /** An uploaded letter's bytes (names are generated by us, so only that pattern is served). */
    public Optional<byte[]> read(String name) {
        if (name == null || !name.matches("[0-9a-z]{15}-\\d{4}-\\d{2}-\\d+\\.pdf")) {
            return Optional.empty();
        }
        Path p = uploads.resolve(name);
        try {
            return Files.exists(p) ? Optional.of(Files.readAllBytes(p)) : Optional.empty();
        } catch (IOException e) {
            return Optional.empty();
        }
    }
}
